export const options = [
  { value: 'FastFoods', label: 'Фастфуд' },
  { value: 'Deserts', label: 'Десерты' },
  { value: 'Vegan', label: 'Вегетерианская' },
  { value: 'Asian', label: 'Азиатская' },
  { value: 'American', label: 'Американская' },
  { value: 'Vostochnaya', label: 'Восточная' },
  { value: 'China', label: 'Китайская' },
  { value: 'Japan', label: 'Японская' },
  { value: 'Korean', label: 'Корейская' },
  { value: 'Vetnam', label: 'Вьетнамская' },
  { value: 'Indian', label: 'Индийская' },
  { value: 'Uzbeckistan', label: 'Узбекская' },
  { value: 'Kyrgyzstan', label: 'Кыргызская' },
]
